---
title: "Additional exercises"
output:
  html_document:
    theme: united
    highlight: zenburn
---

```{r, include = FALSE}
i <- 0
```

Put all of your working into a well-commented (lot's of `#`) and organised script. Once finished, you should be able to restart R and rerun your script without errors. Make sure you try doing this. 


### Question `r {i <- i + 1; i}`

This question uses what we learnt about manipulating vectors in the first two workshops

*Brief Background:* The unified neutral theory of biodiversity is a hypothesis that an individual’s species identity is not related to its survival or fitness.  Under neutral theory, mortality and recruitment are random and population size is only constrained by a maximum community size.  While we know that species traits are important at small spatial scales, neutral theory is interesting because it describes many of the patterns we see at larger scales. 

Here you will simulate a very simple tree community under neutral theory. The basic idea is that we label tree "species" and then let them "reproduce" at random (i.e. we imagine they are all the same). Here are the steps to build a very basic simulation of a neutral community:

a)	Create a character vector containing the letters “a” through “j” and assign it to the name `comm`. This will represent the community, with each element representing an individual and each letter representing a species. **Hint:** use the inbuilt `letters` vector.

b)	Calculate the species richness of this community. Species richness is just the number of unique species in the community. **Hint:** use functions `unique` and `length`.

c)	This bit is quite tricky. We need to be able to choose a random individual to successfully reproduce at each time step. Work out how to select out a random element of `comm` (using R of course!). **Hint:** Use the `sample` function, working with the `x` and `size` arguments. 

d)	We also need to select a random individual to die and be replaced at each time step. To do this, pick out one number at random from the sequence generated by `1:10` (use the same trick you learned above). This will give you the index (i.e. position) of the element to be replaced.

e)	Use square bracket (`[]`) indexing and your answer to (d) to pick out the letter of the individual in `comm` to be replaced.

f)	Combine your answers to (c) and (e) to replace a random element with another. **Hint:** use assignment---the thing on the left to be replaced by the thing on the right.

g)	Run the last step (f) a further 9 times, what has happened to the species richness? What would happen to this community given enough time steps?



### Question `r {i <- i + 1; i}`

This series of questions is based on the `dplyr` workshops from weeks 3 and 4. Use the built in iris data set in R to answer these questions. Remind yourself of what this data set looks like using the glimpse function. 

a) How many different species does this data set contain measurements on? **Hint** use the length and unique functions

b) Select the two columns containing measurements of petal size. **Hint** remember that there are various helper functions that go with select.

c) Select all of the columns except `Sepal.Length` **Hint** remember we can choose which columns to exclude instead of which to keep.

d) Calculate the petal and sepal area for each individual. On average which species has the smallest petal area? Does the same species have the smallest average sepal area?

### Question `r {i <- i + 1; i}`

This series of questions is based mainly on the `dplyr` workshop from week 4. 

Here we're going to use a builtin dataset in R called `ChickWeight`. These data are from an experiment on the effect of diet on early chick growth. Have a look at what this data set looks like using the glimpse function. You can also look at the helpfile for this data set using the `?` function.

a) How many different diets were used in this experiment? How many chicks were fed each diet?

b) How many chicks weighed over 300g at the end of the study? Which was the earliest day on which at least one chick weighed over 300g?

c) Calculate the mean weight on the first and last day of the study for each diet. Which diet had the heaviest chicks on average at the end of the study?

d) Calculate the difference between the starting weight and end weight for each individual chick that survived the whole study period. **Hint** you could do this in several steps. Think about how to extract just the first and last weights first.

e) Which individual chick gained the most weight over the study period?

f) On average which diet saw the largest increase in weight over the study period?



