<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>APS 135: Introduction to Exploratory Data Analysis with R</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Course book for Introduction to Exploratory Data Analysis with R (APS 135) in the Department of Animal and Plant Sciences, University of Sheffield.">
  <meta name="generator" content="bookdown 0.3 and GitBook 2.6.7">

  <meta property="og:title" content="APS 135: Introduction to Exploratory Data Analysis with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course book for Introduction to Exploratory Data Analysis with R (APS 135) in the Department of Animal and Plant Sciences, University of Sheffield." />
  <meta name="github-repo" content="dzchilds/eda-for-bio" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="APS 135: Introduction to Exploratory Data Analysis with R" />
  
  <meta name="twitter:description" content="Course book for Introduction to Exploratory Data Analysis with R (APS 135) in the Department of Animal and Plant Sciences, University of Sheffield." />
  

<meta name="author" content="Dylan Z. Childs">


<meta name="date" content="2017-03-09">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="helper-functions.html">
<link rel="next" href="building-piplines.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<style type="text/css">

.action, .warning, .info, .speed {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  background: #f5f5f5 5px center/3em no-repeat;
}
.action {
  background-image: url("./images/action.png");
}
.warning {
  background-image: url("./images/warning.png");
}
.info {
  background-image: url("./images/info.png");
}
.speed {
  background-image: url("./images/speed.png");
}


</style>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">APS 135 (R course)</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Information and overview</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#aims"><i class="fa fa-check"></i>Aims</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#topics"><i class="fa fa-check"></i>Topics</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#how-to-use-the-book"><i class="fa fa-check"></i>How to use the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#getting-help"><i class="fa fa-check"></i>Getting help</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#updates"><i class="fa fa-check"></i>Updates</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="get-up-and-running-with-r-and-rstudio.html"><a href="get-up-and-running-with-r-and-rstudio.html"><i class="fa fa-check"></i>Get up and running with R and RStudio</a><ul>
<li class="chapter" data-level="" data-path="get-up-and-running-with-r-and-rstudio.html"><a href="get-up-and-running-with-r-and-rstudio.html#what-is-r"><i class="fa fa-check"></i>What is R?</a><ul>
<li class="chapter" data-level="" data-path="get-up-and-running-with-r-and-rstudio.html"><a href="get-up-and-running-with-r-and-rstudio.html#getting-and-installing-r"><i class="fa fa-check"></i>Getting and installing R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="get-up-and-running-with-r-and-rstudio.html"><a href="get-up-and-running-with-r-and-rstudio.html#what-is-rstudio-and-why-use-it"><i class="fa fa-check"></i>What is RStudio (and why use it)?</a><ul>
<li class="chapter" data-level="" data-path="get-up-and-running-with-r-and-rstudio.html"><a href="get-up-and-running-with-r-and-rstudio.html#getting-and-installing-rstudio"><i class="fa fa-check"></i>Getting and installing RStudio</a></li>
<li class="chapter" data-level="" data-path="get-up-and-running-with-r-and-rstudio.html"><a href="get-up-and-running-with-r-and-rstudio.html#the-anatomy-of-rstudio"><i class="fa fa-check"></i>The anatomy of RStudio</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="get-up-and-running-with-r-and-rstudio.html"><a href="get-up-and-running-with-r-and-rstudio.html#working-at-the-console"><i class="fa fa-check"></i>Working at the Console</a></li>
</ul></li>
<li class="part"><span><b>I Introduction to R</b></span></li>
<li class="chapter" data-level="1" data-path="a-quick-introduction-to-r.html"><a href="a-quick-introduction-to-r.html"><i class="fa fa-check"></i><b>1</b> A quick introduction to R</a><ul>
<li class="chapter" data-level="1.1" data-path="a-quick-introduction-to-r.html"><a href="a-quick-introduction-to-r.html#r-calculator"><i class="fa fa-check"></i><b>1.1</b> Using R as a big calculator</a><ul>
<li class="chapter" data-level="1.1.1" data-path="a-quick-introduction-to-r.html"><a href="a-quick-introduction-to-r.html#basic-arithmetic"><i class="fa fa-check"></i><b>1.1.1</b> Basic arithmetic</a></li>
<li class="chapter" data-level="1.1.2" data-path="a-quick-introduction-to-r.html"><a href="a-quick-introduction-to-r.html#problematic-calculations"><i class="fa fa-check"></i><b>1.1.2</b> Problematic calculations</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="a-quick-introduction-to-r.html"><a href="a-quick-introduction-to-r.html#assignment"><i class="fa fa-check"></i><b>1.2</b> Storing and reusing results</a></li>
<li class="chapter" data-level="1.3" data-path="a-quick-introduction-to-r.html"><a href="a-quick-introduction-to-r.html#how-does-assignment-work"><i class="fa fa-check"></i><b>1.3</b> How does assignment work?</a></li>
<li class="chapter" data-level="1.4" data-path="a-quick-introduction-to-r.html"><a href="a-quick-introduction-to-r.html#global-environment"><i class="fa fa-check"></i><b>1.4</b> Global environment</a></li>
<li class="chapter" data-level="1.5" data-path="a-quick-introduction-to-r.html"><a href="a-quick-introduction-to-r.html#naming-rules-and-conventions"><i class="fa fa-check"></i><b>1.5</b> Naming rules and conventions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="scripts.html"><a href="scripts.html"><i class="fa fa-check"></i><b>2</b> Building scripts</a><ul>
<li class="chapter" data-level="2.1" data-path="scripts.html"><a href="scripts.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="scripts.html"><a href="scripts.html#writing-scripts-in-rstudio"><i class="fa fa-check"></i><b>2.2</b> Writing scripts in RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="scripts.html"><a href="scripts.html#running-scripts-in-rstudio"><i class="fa fa-check"></i><b>2.3</b> Running scripts in RStudio</a></li>
<li class="chapter" data-level="2.4" data-path="scripts.html"><a href="scripts.html#spotting-problems"><i class="fa fa-check"></i><b>2.4</b> Spotting problems</a><ul>
<li class="chapter" data-level="2.4.1" data-path="scripts.html"><a href="scripts.html#the-dreaded"><i class="fa fa-check"></i><b>2.4.1</b> The dreaded <code>+</code></a></li>
<li class="chapter" data-level="2.4.2" data-path="scripts.html"><a href="scripts.html#errors"><i class="fa fa-check"></i><b>2.4.2</b> Errors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="using-functions.html"><a href="using-functions.html"><i class="fa fa-check"></i><b>3</b> Using functions</a><ul>
<li class="chapter" data-level="3.1" data-path="using-functions.html"><a href="using-functions.html#intro-functions"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="using-functions.html"><a href="using-functions.html#functions-and-arguments"><i class="fa fa-check"></i><b>3.2</b> Functions and arguments</a></li>
<li class="chapter" data-level="3.3" data-path="using-functions.html"><a href="using-functions.html#evaluating-arguments-and-returning-results"><i class="fa fa-check"></i><b>3.3</b> Evaluating arguments and returning results</a></li>
<li class="chapter" data-level="3.4" data-path="using-functions.html"><a href="using-functions.html#functions-do-not-have-side-effects"><i class="fa fa-check"></i><b>3.4</b> Functions do not have “side effects”</a></li>
<li class="chapter" data-level="3.5" data-path="using-functions.html"><a href="using-functions.html#combining-functions"><i class="fa fa-check"></i><b>3.5</b> Combining functions</a></li>
<li class="chapter" data-level="3.6" data-path="using-functions.html"><a href="using-functions.html#function-arguments"><i class="fa fa-check"></i><b>3.6</b> Specifying function arguments</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="numeric-vectors.html"><a href="numeric-vectors.html"><i class="fa fa-check"></i><b>4</b> Numeric vectors</a><ul>
<li class="chapter" data-level="4.1" data-path="numeric-vectors.html"><a href="numeric-vectors.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="numeric-vectors.html"><a href="numeric-vectors.html#atomic-vectors"><i class="fa fa-check"></i><b>4.2</b> Atomic vectors</a></li>
<li class="chapter" data-level="4.3" data-path="numeric-vectors.html"><a href="numeric-vectors.html#intro-vectors"><i class="fa fa-check"></i><b>4.3</b> Numeric vectors</a></li>
<li class="chapter" data-level="4.4" data-path="numeric-vectors.html"><a href="numeric-vectors.html#constructing-numeric-vectors"><i class="fa fa-check"></i><b>4.4</b> Constructing numeric vectors</a></li>
<li class="chapter" data-level="4.5" data-path="numeric-vectors.html"><a href="numeric-vectors.html#named-vectors"><i class="fa fa-check"></i><b>4.5</b> Named vectors</a></li>
<li class="chapter" data-level="4.6" data-path="numeric-vectors.html"><a href="numeric-vectors.html#generating-sequences-of-numbers"><i class="fa fa-check"></i><b>4.6</b> Generating sequences of numbers</a><ul>
<li class="chapter" data-level="4.6.1" data-path="numeric-vectors.html"><a href="numeric-vectors.html#generating-sequences-of-numbers-1"><i class="fa fa-check"></i><b>4.6.1</b> Generating sequences of numbers</a></li>
<li class="chapter" data-level="4.6.2" data-path="numeric-vectors.html"><a href="numeric-vectors.html#generating-repeated-sequences-of-numbers"><i class="fa fa-check"></i><b>4.6.2</b> Generating repeated sequences of numbers</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="numeric-vectors.html"><a href="numeric-vectors.html#vectorised-operations"><i class="fa fa-check"></i><b>4.7</b> Vectorised operations</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="other-kinds-of-vectors.html"><a href="other-kinds-of-vectors.html"><i class="fa fa-check"></i><b>5</b> Other kinds of vectors</a><ul>
<li class="chapter" data-level="5.1" data-path="other-kinds-of-vectors.html"><a href="other-kinds-of-vectors.html#other-vectors"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="other-kinds-of-vectors.html"><a href="other-kinds-of-vectors.html#character-vectors"><i class="fa fa-check"></i><b>5.2</b> Character vectors</a></li>
<li class="chapter" data-level="5.3" data-path="other-kinds-of-vectors.html"><a href="other-kinds-of-vectors.html#logical-vectors"><i class="fa fa-check"></i><b>5.3</b> Logical vectors</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="extracting-subsets-of-vectors.html"><a href="extracting-subsets-of-vectors.html"><i class="fa fa-check"></i><b>6</b> Extracting subsets of vectors</a><ul>
<li class="chapter" data-level="6.1" data-path="other-kinds-of-vectors.html"><a href="other-kinds-of-vectors.html#other-vectors"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="extracting-subsets-of-vectors.html"><a href="extracting-subsets-of-vectors.html#subsetting-by-position"><i class="fa fa-check"></i><b>6.2</b> Subsetting by position</a></li>
<li class="chapter" data-level="6.3" data-path="extracting-subsets-of-vectors.html"><a href="extracting-subsets-of-vectors.html#subsetting-with-logical-operators"><i class="fa fa-check"></i><b>6.3</b> Subsetting with logical operators</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="getting-help-1.html"><a href="getting-help-1.html"><i class="fa fa-check"></i><b>7</b> Getting help</a><ul>
<li class="chapter" data-level="7.1" data-path="getting-help-1.html"><a href="getting-help-1.html#console-help"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="getting-help-1.html"><a href="getting-help-1.html#browsing-the-help-system"><i class="fa fa-check"></i><b>7.2</b> Browsing the help system</a></li>
<li class="chapter" data-level="7.3" data-path="getting-help-1.html"><a href="getting-help-1.html#searching-for-help-files"><i class="fa fa-check"></i><b>7.3</b> Searching for help files</a></li>
<li class="chapter" data-level="7.4" data-path="getting-help-1.html"><a href="getting-help-1.html#nav-help"><i class="fa fa-check"></i><b>7.4</b> Navigating help files</a></li>
<li class="chapter" data-level="7.5" data-path="getting-help-1.html"><a href="getting-help-1.html#vignettes"><i class="fa fa-check"></i><b>7.5</b> Vignettes and demos</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>8</b> Packages</a><ul>
<li class="chapter" data-level="8.1" data-path="packages.html"><a href="packages.html#package-system"><i class="fa fa-check"></i><b>8.1</b> The R package system</a></li>
<li class="chapter" data-level="8.2" data-path="packages.html"><a href="packages.html#task-views"><i class="fa fa-check"></i><b>8.2</b> Task views</a></li>
<li class="chapter" data-level="8.3" data-path="packages.html"><a href="packages.html#use-packages"><i class="fa fa-check"></i><b>8.3</b> Using packages</a><ul>
<li class="chapter" data-level="8.3.1" data-path="packages.html"><a href="packages.html#viewing-installed-packages"><i class="fa fa-check"></i><b>8.3.1</b> Viewing installed packages</a></li>
<li class="chapter" data-level="8.3.2" data-path="packages.html"><a href="packages.html#installing-packages"><i class="fa fa-check"></i><b>8.3.2</b> Installing packages</a></li>
<li class="chapter" data-level="8.3.3" data-path="packages.html"><a href="packages.html#loading-and-attaching-packages"><i class="fa fa-check"></i><b>8.3.3</b> Loading and attaching packages</a></li>
<li class="chapter" data-level="8.3.4" data-path="packages.html"><a href="packages.html#an-analogy"><i class="fa fa-check"></i><b>8.3.4</b> An analogy</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Data Wrangling</b></span></li>
<li class="chapter" data-level="9" data-path="data-frames.html"><a href="data-frames.html"><i class="fa fa-check"></i><b>9</b> Data frames</a><ul>
<li class="chapter" data-level="9.1" data-path="data-frames.html"><a href="data-frames.html#introduction-2"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="data-frames.html"><a href="data-frames.html#data-frames-intro"><i class="fa fa-check"></i><b>9.2</b> Data frames</a></li>
<li class="chapter" data-level="9.3" data-path="data-frames.html"><a href="data-frames.html#exploring-data-frames"><i class="fa fa-check"></i><b>9.3</b> Exploring data frames</a></li>
<li class="chapter" data-level="9.4" data-path="data-frames.html"><a href="data-frames.html#extract-data"><i class="fa fa-check"></i><b>9.4</b> Extracting data from data frames</a><ul>
<li class="chapter" data-level="9.4.1" data-path="data-frames.html"><a href="data-frames.html#extracting-and-adding-a-single-variable"><i class="fa fa-check"></i><b>9.4.1</b> Extracting and adding a single variable</a></li>
<li class="chapter" data-level="9.4.2" data-path="data-frames.html"><a href="data-frames.html#adding-a-variable-to-a-data-frame"><i class="fa fa-check"></i><b>9.4.2</b> Adding a variable to a data frame</a></li>
<li class="chapter" data-level="9.4.3" data-path="data-frames.html"><a href="data-frames.html#subsetting-data-frames"><i class="fa fa-check"></i><b>9.4.3</b> Subsetting data frames</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="data-frames.html"><a href="data-frames.html#final-words"><i class="fa fa-check"></i><b>9.5</b> Final words</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="working-directories-and-data-files.html"><a href="working-directories-and-data-files.html"><i class="fa fa-check"></i><b>10</b> Working directories and data files</a><ul>
<li class="chapter" data-level="10.1" data-path="working-directories-and-data-files.html"><a href="working-directories-and-data-files.html#introduction-3"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="working-directories-and-data-files.html"><a href="working-directories-and-data-files.html#data-files-the-csv-format"><i class="fa fa-check"></i><b>10.2</b> Data files: the CSV format</a><ul>
<li class="chapter" data-level="10.2.1" data-path="working-directories-and-data-files.html"><a href="working-directories-and-data-files.html#exporting-csv-files-from-excel"><i class="fa fa-check"></i><b>10.2.1</b> Exporting CSV files from Excel</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="working-directories-and-data-files.html"><a href="working-directories-and-data-files.html#the-working-directory"><i class="fa fa-check"></i><b>10.3</b> The working directory</a></li>
<li class="chapter" data-level="10.4" data-path="working-directories-and-data-files.html"><a href="working-directories-and-data-files.html#importing-data-with-read.csv"><i class="fa fa-check"></i><b>10.4</b> Importing data with <code>read.csv</code></a></li>
<li class="chapter" data-level="10.5" data-path="working-directories-and-data-files.html"><a href="working-directories-and-data-files.html#importing-data-with-rstudio-avoid-this"><i class="fa fa-check"></i><b>10.5</b> Importing data with RStudio (Avoid this!)</a></li>
<li class="chapter" data-level="10.6" data-path="working-directories-and-data-files.html"><a href="working-directories-and-data-files.html#package-data"><i class="fa fa-check"></i><b>10.6</b> Package data</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="dplyr-and-the-tidy-data-concept.html"><a href="dplyr-and-the-tidy-data-concept.html"><i class="fa fa-check"></i><b>11</b> <strong>dplyr</strong> and the tidy data concept</a><ul>
<li class="chapter" data-level="11.1" data-path="dplyr-and-the-tidy-data-concept.html"><a href="dplyr-and-the-tidy-data-concept.html#introduction-4"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="dplyr-and-the-tidy-data-concept.html"><a href="dplyr-and-the-tidy-data-concept.html#why-dplyr"><i class="fa fa-check"></i><b>11.2</b> The value of <strong>dplyr</strong></a></li>
<li class="chapter" data-level="11.3" data-path="dplyr-and-the-tidy-data-concept.html"><a href="dplyr-and-the-tidy-data-concept.html#tidy-data"><i class="fa fa-check"></i><b>11.3</b> Tidy data</a></li>
<li class="chapter" data-level="11.4" data-path="dplyr-and-the-tidy-data-concept.html"><a href="dplyr-and-the-tidy-data-concept.html#more-dplyr"><i class="fa fa-check"></i><b>11.4</b> A quick look at <strong>dplyr</strong></a><ul>
<li class="chapter" data-level="11.4.1" data-path="dplyr-and-the-tidy-data-concept.html"><a href="dplyr-and-the-tidy-data-concept.html#tibble-tbl-objects"><i class="fa fa-check"></i><b>11.4.1</b> Tibble (<code>tbl</code>) objects</a></li>
<li class="chapter" data-level="11.4.2" data-path="dplyr-and-the-tidy-data-concept.html"><a href="dplyr-and-the-tidy-data-concept.html#the-glimpse-function"><i class="fa fa-check"></i><b>11.4.2</b> The <code>glimpse</code> function</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="working-with-variables.html"><a href="working-with-variables.html"><i class="fa fa-check"></i><b>12</b> Working with variables</a><ul>
<li class="chapter" data-level="12.1" data-path="working-with-variables.html"><a href="working-with-variables.html#introduction-5"><i class="fa fa-check"></i><b>12.1</b> Introduction</a><ul>
<li class="chapter" data-level="12.1.1" data-path="working-with-variables.html"><a href="working-with-variables.html#getting-ready"><i class="fa fa-check"></i><b>12.1.1</b> Getting ready</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="working-with-variables.html"><a href="working-with-variables.html#subset-variables-with-select"><i class="fa fa-check"></i><b>12.2</b> Subset variables with <code>select</code></a><ul>
<li class="chapter" data-level="12.2.1" data-path="working-with-variables.html"><a href="working-with-variables.html#renaming-variables-with-select-and-rename"><i class="fa fa-check"></i><b>12.2.1</b> Renaming variables with <code>select</code> and <code>rename</code></a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="working-with-variables.html"><a href="working-with-variables.html#creating-variables-with-mutate"><i class="fa fa-check"></i><b>12.3</b> Creating variables with <code>mutate</code></a><ul>
<li class="chapter" data-level="12.3.1" data-path="working-with-variables.html"><a href="working-with-variables.html#transforming-and-dropping-variables"><i class="fa fa-check"></i><b>12.3.1</b> Transforming and dropping variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="working-with-observations.html"><a href="working-with-observations.html"><i class="fa fa-check"></i><b>13</b> Working with observations</a><ul>
<li class="chapter" data-level="13.1" data-path="working-with-observations.html"><a href="working-with-observations.html#introduction-6"><i class="fa fa-check"></i><b>13.1</b> Introduction</a><ul>
<li class="chapter" data-level="13.1.1" data-path="working-with-observations.html"><a href="working-with-observations.html#getting-ready-1"><i class="fa fa-check"></i><b>13.1.1</b> Getting ready</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="working-with-observations.html"><a href="working-with-observations.html#subset-observations-with-filter"><i class="fa fa-check"></i><b>13.2</b> Subset observations with <code>filter</code></a></li>
<li class="chapter" data-level="13.3" data-path="working-with-observations.html"><a href="working-with-observations.html#reording-observations-with-arrange"><i class="fa fa-check"></i><b>13.3</b> Reording observations with <code>arrange</code></a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="helper-functions.html"><a href="helper-functions.html"><i class="fa fa-check"></i><b>14</b> Helper functions</a><ul>
<li class="chapter" data-level="14.1" data-path="helper-functions.html"><a href="helper-functions.html#introduction-7"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="helper-functions.html"><a href="helper-functions.html#working-with-select"><i class="fa fa-check"></i><b>14.2</b> Working with <code>select</code></a></li>
<li class="chapter" data-level="14.3" data-path="helper-functions.html"><a href="helper-functions.html#working-with-mutate-and-transmute"><i class="fa fa-check"></i><b>14.3</b> Working with <code>mutate</code> and <code>transmute</code></a></li>
<li class="chapter" data-level="14.4" data-path="helper-functions.html"><a href="helper-functions.html#working-with-filter"><i class="fa fa-check"></i><b>14.4</b> Working with <code>filter</code></a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="grouping-and-summarising-data.html"><a href="grouping-and-summarising-data.html"><i class="fa fa-check"></i><b>15</b> Grouping and summarising data</a><ul>
<li class="chapter" data-level="15.0.1" data-path="grouping-and-summarising-data.html"><a href="grouping-and-summarising-data.html#getting-ready-2"><i class="fa fa-check"></i><b>15.0.1</b> Getting ready</a></li>
<li class="chapter" data-level="15.1" data-path="grouping-and-summarising-data.html"><a href="grouping-and-summarising-data.html#summarising-variables-with-summarise"><i class="fa fa-check"></i><b>15.1</b> Summarising variables with <code>summarise</code></a><ul>
<li class="chapter" data-level="15.1.1" data-path="grouping-and-summarising-data.html"><a href="grouping-and-summarising-data.html#helper-functions-1"><i class="fa fa-check"></i><b>15.1.1</b> Helper functions</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="grouping-and-summarising-data.html"><a href="grouping-and-summarising-data.html#grouped-operations-using-group_by"><i class="fa fa-check"></i><b>15.2</b> Grouped operations using <code>group_by</code></a><ul>
<li class="chapter" data-level="15.2.1" data-path="grouping-and-summarising-data.html"><a href="grouping-and-summarising-data.html#more-than-one-grouping-variable"><i class="fa fa-check"></i><b>15.2.1</b> More than one grouping variable</a></li>
<li class="chapter" data-level="15.2.2" data-path="grouping-and-summarising-data.html"><a href="grouping-and-summarising-data.html#using-group_by-with-other-verbs"><i class="fa fa-check"></i><b>15.2.2</b> Using <code>group_by</code> with other verbs</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="grouping-and-summarising-data.html"><a href="grouping-and-summarising-data.html#removing-grouping-information"><i class="fa fa-check"></i><b>15.3</b> Removing grouping information</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="building-piplines.html"><a href="building-piplines.html"><i class="fa fa-check"></i><b>16</b> Building piplines</a><ul>
<li class="chapter" data-level="16.1" data-path="building-piplines.html"><a href="building-piplines.html#why-do-we-need-pipes"><i class="fa fa-check"></i><b>16.1</b> Why do we need ‘pipes’?</a></li>
</ul></li>
<li class="part"><span><b>III Exporing Data</b></span></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">APS 135: Introduction to Exploratory Data Analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="grouping-and-summarising-data" class="section level1">
<h1><span class="header-section-number">Chapter 15</span> Grouping and summarising data</h1>
<p>This chapter will explore the <code>summarise</code> and <code>group_by</code> verbs. These two verbs are considered together because they are often used together, and their usage is quite distinct from the other <strong>dplyr</strong> verbs we’ve encountered:</p>
<ul>
<li><p>The <code>group_by</code> function adds information into a data object (e.g. a data frame or tibble), which makes subsequent calculations happen on a group-specific basis.</p></li>
<li><p>The <code>summarise</code> function is a data reduction function calculates single-number summaries of one or more variables, respecting the group structure if present.</p></li>
</ul>
<div id="getting-ready-2" class="section level3">
<h3><span class="header-section-number">15.0.1</span> Getting ready</h3>
<p>We can start a new script by loading and attaching the <strong>dplyr</strong> package:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;dplyr&quot;</span>)</code></pre></div>
<p>We’re going to use both the <code>storms</code> and <code>iris</code> data sets in the <strong>nasaweather</strong> and <strong>datasets</strong> packages, respectively. The <strong>datasets</strong> package ships is automatically loaded and attached at start up, so we need to make the <strong>nasaweather</strong> package available:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;nasaweather&quot;</span>)</code></pre></div>
<p>Finally, let’s convert both data sets to a tibble so they print to the Console cleanly:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">storms_tbl &lt;-<span class="st"> </span><span class="kw">tbl_df</span>(storms)
iris_tbl   &lt;-<span class="st"> </span><span class="kw">tbl_df</span>(iris)</code></pre></div>
</div>
<div id="summarising-variables-with-summarise" class="section level2">
<h2><span class="header-section-number">15.1</span> Summarising variables with <code>summarise</code></h2>
<p>We use <code>summarise</code> to <strong>calculate summaries of variables</strong> in a an object containing our data. We do this kind of calculation all the time when analysing data. In terms of pseudo-code, usage of <code>summarise</code> looks like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(data_set, &lt;expression1&gt;, &lt;expression2&gt;, ...)</code></pre></div>
<p>The first argument, <code>data_set</code>, must be the name of the data frame or tibble containing our data. We then include a series of one or more additional arguments, each of these is a valid R expression involving at least one variable in <code>data_set</code>. These are given by the pseudo-code placeholder <code>&lt;expression1&gt;, &lt;expression2&gt;, ...</code>, where <code>&lt;expression1&gt;</code> and <code>&lt;expression2&gt;</code> represent the first two expressions, and the <code>...</code> is acting as placeholder for the remaining expressions. These expressions can be any calculation involving R functions. The only constraint is that they must generate <strong>a single value</strong> when evaluated.</p>
<p>That last sentence was important. It’s easy to use <code>summarise</code> if can we remember one thing: <code>summarise</code> is designed to work with functions that take a vector as their input and return a single value (i.e. a vector of length one). Any calculation that does this can be used with <code>summarise</code>.</p>
<p>The <code>summarise</code> verb is best understood by example. The R function called <code>mean</code> takes a vector of numbers (several numbers) and calculates their arithmetic mean (one number). We can use <code>mean</code> with <code>summarise</code> to calculate the mean of the <code>Petal.Length</code> and <code>Petal.Width</code> variables in <code>iris_tbl</code> like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(iris_tbl, <span class="kw">mean</span>(Petal.Length), <span class="kw">mean</span>(Petal.Width))</code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   `mean(Petal.Length)` `mean(Petal.Width)`
##                  &lt;dbl&gt;               &lt;dbl&gt;
## 1                3.758            1.199333</code></pre>
<p>Notice what kind of object <code>summarise</code> returns: it’s a tibble with only one row and two columns. There are two columns because we calculated two means, and there is one row containing these means. Simple. There are a few other things to note about how <code>summarise</code> works:</p>
<ul>
<li><p>As with all <strong>dplyr</strong> functions, the expression that performs the required summary calculation is not surrounded by quotes because it is an expression that it “does some calculations”.</p></li>
<li><p>The order of the expression in the resulting tibble is the same as the order in which they were used as arguments.</p></li>
<li><p>Even though the dimensions of the output object have changed, <code>summarise</code> returns the same kind of data object as its input. It returns a data frame if our data was originally in a data frame, or a tibble if it was in a tibble.</p></li>
</ul>
<p>Notice that <code>summarise</code> used the expressions to name the variables. Variable names like <code>mean(Petal.Length)</code> and <code>mean(Petal.Width)</code> are not very helpful. They’re quite long for one. More problematically, they contain special reserved characters like <code>(</code>, which makes referring to columns in the resulting tibble more difficult than it needs to be:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># make a summary tibble an assign it a name</span>
iris_means &lt;-<span class="st"> </span><span class="kw">summarise</span>(iris_tbl, <span class="kw">mean</span>(Petal.Length), <span class="kw">mean</span>(Petal.Width))
<span class="co"># extract the mean petal length</span>
iris_means$<span class="st">`</span><span class="dt">mean(Petal.Length)</span><span class="st">`</span></code></pre></div>
<pre><code>## [1] 3.758</code></pre>
<p>We have to place ‘back ticks’ (as above) or ordinary quotes around the name to extract the new column when it includes special characters.</p>
<p>It’s better to avoid using the default names. The <code>summarise</code> function can name the new variables at the same time as they are created. Predictably, we do this by naming the arguments using <code>=</code>, placing the name we require on the left hand side. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(iris_tbl, <span class="dt">Mean_PL =</span> <span class="kw">mean</span>(Petal.Length), <span class="dt">Mean_PW =</span> <span class="kw">mean</span>(Petal.Width))</code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   Mean_PL  Mean_PW
##     &lt;dbl&gt;    &lt;dbl&gt;
## 1   3.758 1.199333</code></pre>
<p>There are very many base R functions that can be used with <code>summarise</code>. A few useful ones for calculating summaries of numeric variables are:</p>
<ul>
<li><p><code>min</code> and <code>max</code> calculate the minimum and maximum values of a vector.</p></li>
<li><p><code>mean</code> and <code>median</code> calculate the mean and median of a numeric vector.</p></li>
<li><p><code>sd</code> and <code>var</code> calculate the standard deviation and variance of a numeric vector.</p></li>
</ul>
<p>We can combine more than one function in a <code>summarise</code> expression as long as it returns a single number. This means we can do arbitrarily complicated calculations in a single step. For example, if we need to know the ratio of the mean and median values of petal length and petal width in <code>iris_tbl</code>, we use:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(iris_tbl,
          <span class="dt">Mn_Md_PL =</span> <span class="kw">mean</span>(Petal.Length) /<span class="st"> </span><span class="kw">median</span>(Petal.Length),
          <span class="dt">Mn_Md_PW =</span> <span class="kw">mean</span>(Petal.Width)  /<span class="st"> </span><span class="kw">median</span>(Petal.Width))</code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   Mn_Md_PL  Mn_Md_PW
##      &lt;dbl&gt;     &lt;dbl&gt;
## 1 0.863908 0.9225641</code></pre>
<p>Notice that we placed each argument on a separate line in this example. This is just a style issue—we don’t have to do this, but since R doesn’t care about white space, we can use new lines and spaces to keep everything a bit more more human-readable. It pays to organise <code>summarise</code> calculations like this as they become longer. It allows us to see the logic of the calculations more easily, and helps us spot potential errors when they occur.</p>
<div id="helper-functions-1" class="section level3">
<h3><span class="header-section-number">15.1.1</span> Helper functions</h3>
<p>There are a small number <strong>dplyr</strong> helper functions that can be used with <code>summarise</code>. These generally provide summaries that aren’t available directly using base R functions. For example, the <code>n_distinct</code> function is used to calculate the number of distinct values in a variable:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(iris_tbl, <span class="dt">Num.PL.Vals =</span> <span class="kw">n_distinct</span>(Petal.Length))</code></pre></div>
<pre><code>## # A tibble: 1 × 1
##   Num.PL.Vals
##         &lt;int&gt;
## 1          43</code></pre>
<p>This tells us that there are 43 unique values of <code>Petal.Length</code>. We won’t explore any others here. The <a href="http://www.rstudio.com/resources/cheatsheets/">handy cheat sheat</a> is worth looking over to see what additional options are available.</p>
</div>
</div>
<div id="grouped-operations-using-group_by" class="section level2">
<h2><span class="header-section-number">15.2</span> Grouped operations using <code>group_by</code></h2>
<p>Performing a calculation with one or more variables over the whole data set is useful, but very often we also need to carry out an operation on different subsets of our data. For example, it’s probably more useful to know how the mean sepal and petal traits vary among the different species in the <code>iris_tbl</code> data set, rather than knowing the overall mean of these traits. We could calculate separate means by using <code>filter</code> to create different subsets of <code>iris_tbl</code>, and then using <code>summary</code> on each of these to calculate the relevant means. This would get the job done, but it’s not very efficient and very soon becomes tiresome when we have to work with many groups.</p>
<p>The <code>group_by</code> function provides a more elegant solution to this kind of problem. It doesn’t do all that much on its own though. All the <code>group_by</code> function does is add a bit of grouping information to a tibble or data frame. In effect, it defines subsets of data on the basis of one or more <strong>grouping variables</strong>. The magic happens when the grouped object is used with a <strong>dplyr</strong> verb like <code>summarise</code> or <code>mutate</code>. Once a data frame or tibble has been tagged with grouping information, operations that involve these (and other) verbs are carried out on separate subsets of the data, where the subsets correspond to the different values of the grouping variable(s).</p>
<p>Basic usage of <code>group_by</code> looks like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">group_by</span>(data_set, vname1, vname2, ...)</code></pre></div>
<p>The first argument, <code>data_set</code> (“data object”), must be the name of the object containing our data. We then have to include one or more additional arguments, where each of these is the name of a variable in <code>data_set</code>. I have expressed this as <code>vname1, vname2, ...</code>, where <code>vname1</code> and <code>vname2</code> are names of the first two variables, and the <code>...</code> is acting as placeholder for the remaining variables.</p>
<p>As usual, it’s much easier to understand how <code>group_by</code> works once we’ve seen it in action. We’ll illustrate <code>group_by</code> by using it alongside <code>summarise</code> with the <code>storms_tbl</code> data set. We’re aiming to calculate the mean wind speed for every type of storm. The first step is to use <code>group_by</code> to add grouping information to <code>storms_tbl</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">group_by</span>(storms_tbl, type)</code></pre></div>
<pre><code>## Source: local data frame [2,747 x 11]
## Groups: type [4]
## 
##       name  year month   day  hour   lat  long pressure  wind
##      &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;int&gt; &lt;int&gt;
## 1  Allison  1995     6     3     0  17.4 -84.3     1005    30
## 2  Allison  1995     6     3     6  18.3 -84.9     1004    30
## 3  Allison  1995     6     3    12  19.3 -85.7     1003    35
## 4  Allison  1995     6     3    18  20.6 -85.8     1001    40
## 5  Allison  1995     6     4     0  22.0 -86.0      997    50
## 6  Allison  1995     6     4     6  23.3 -86.3      995    60
## 7  Allison  1995     6     4    12  24.7 -86.2      987    65
## 8  Allison  1995     6     4    18  26.2 -86.2      988    65
## 9  Allison  1995     6     5     0  27.6 -86.1      988    65
## 10 Allison  1995     6     5     6  28.5 -85.6      990    60
## # ... with 2,737 more rows, and 2 more variables: type &lt;chr&gt;,
## #   seasday &lt;int&gt;</code></pre>
<p>Compare this to the output produced when we print the original <code>storms_tbl</code> data set:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">storms_tbl</code></pre></div>
<pre><code>## # A tibble: 2,747 × 11
##       name  year month   day  hour   lat  long pressure  wind
##      &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;int&gt; &lt;int&gt;
## 1  Allison  1995     6     3     0  17.4 -84.3     1005    30
## 2  Allison  1995     6     3     6  18.3 -84.9     1004    30
## 3  Allison  1995     6     3    12  19.3 -85.7     1003    35
## 4  Allison  1995     6     3    18  20.6 -85.8     1001    40
## 5  Allison  1995     6     4     0  22.0 -86.0      997    50
## 6  Allison  1995     6     4     6  23.3 -86.3      995    60
## 7  Allison  1995     6     4    12  24.7 -86.2      987    65
## 8  Allison  1995     6     4    18  26.2 -86.2      988    65
## 9  Allison  1995     6     5     0  27.6 -86.1      988    65
## 10 Allison  1995     6     5     6  28.5 -85.6      990    60
## # ... with 2,737 more rows, and 2 more variables: type &lt;chr&gt;,
## #   seasday &lt;int&gt;</code></pre>
<p>There is almost no difference between the printed information. <code>group_by</code> really doesn’t do much on its own. If you are paying close attention you will have noticed that the tibble from <code>group_by(storms_tbl, type)</code> has a little bit of additional information printed at the top: <code>Groups: type [4]</code>. The <code>Groups: type</code> part of this tells us that the tibble is grouped by the <code>type</code> variable and nothing else. The <code>[4]</code> part tells us that there are 4 different groups.</p>
<p>The only thing <code>group_by</code> did was add this grouping information to a copy of <code>storms_tbl</code>. The original <code>storms_tbl</code> object was not altered in any way. If we actually want to do anything useful useful with the result we need to assign it a name so that we can work with it:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">storms_grouped &lt;-<span class="st"> </span><span class="kw">group_by</span>(storms_tbl, type)</code></pre></div>
<p>Now we have a grouped tibble called <code>storms_grouped</code>, where the groups are defined by the values of <code>type</code>. Any operations on this tibble will now be performed on a “by group” basis. To see this in action, we use <code>summarise</code> to calculate the mean wind speed:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(storms_grouped, <span class="dt">mean.wind =</span> <span class="kw">mean</span>(wind))</code></pre></div>
<pre><code>## # A tibble: 4 × 2
##                  type mean.wind
##                 &lt;chr&gt;     &lt;dbl&gt;
## 1       Extratropical  40.06068
## 2           Hurricane  84.65960
## 3 Tropical Depression  27.35867
## 4      Tropical Storm  47.32181</code></pre>
<p>When we used <code>summarise</code> on an ungrouped tibble the result was a tibble with one row: the overall global mean. Now the resulting tibble has four rows, one for each value of <code>type</code>: The <code>type</code> variable in the new tibble tells us what these values are; the <code>mean.wind</code> variable shows the mean wind speed for each value.</p>
<div id="more-than-one-grouping-variable" class="section level3">
<h3><span class="header-section-number">15.2.1</span> More than one grouping variable</h3>
<p>What if we need to calculate summaries using more than one grouping variable? The workflow is unchanged. Let’s assume we want to know the mean wind speed and atmospheric pressure associated with each storm type in each year. We first make a grouped copy of the data set with the appropriate grouping variables:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># group the storms_tbl data by storm year + assign the result a name</span>
storms_grouped &lt;-<span class="st"> </span><span class="kw">group_by</span>(storms_tbl, type, year)
<span class="co"># </span>
storms_grouped</code></pre></div>
<pre><code>## Source: local data frame [2,747 x 11]
## Groups: type, year [24]
## 
##       name  year month   day  hour   lat  long pressure  wind
##      &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;int&gt; &lt;int&gt;
## 1  Allison  1995     6     3     0  17.4 -84.3     1005    30
## 2  Allison  1995     6     3     6  18.3 -84.9     1004    30
## 3  Allison  1995     6     3    12  19.3 -85.7     1003    35
## 4  Allison  1995     6     3    18  20.6 -85.8     1001    40
## 5  Allison  1995     6     4     0  22.0 -86.0      997    50
## 6  Allison  1995     6     4     6  23.3 -86.3      995    60
## 7  Allison  1995     6     4    12  24.7 -86.2      987    65
## 8  Allison  1995     6     4    18  26.2 -86.2      988    65
## 9  Allison  1995     6     5     0  27.6 -86.1      988    65
## 10 Allison  1995     6     5     6  28.5 -85.6      990    60
## # ... with 2,737 more rows, and 2 more variables: type &lt;chr&gt;,
## #   seasday &lt;int&gt;</code></pre>
<p>We grouped the <code>storms_tbl</code> data by <code>type</code> and <code>year</code> and assigned the grouped tibble the name <code>storms_grouped</code>. When we print this to the Console we see <code>Groups: type, year [24]</code> near the top, which tells us that the tibble is grouped by two variables with 24 unique combinations of values. We then calculate the mean wind speed and pressure of each storm type in each year:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summarise</span>(storms_grouped, 
          <span class="dt">mean_wind     =</span> <span class="kw">mean</span>(wind), 
          <span class="dt">mean_pressure =</span> <span class="kw">mean</span>(pressure))</code></pre></div>
<pre><code>## Source: local data frame [24 x 4]
## Groups: type [?]
## 
##             type  year mean_wind mean_pressure
##            &lt;chr&gt; &lt;int&gt;     &lt;dbl&gt;         &lt;dbl&gt;
## 1  Extratropical  1995  38.67521      995.2991
## 2  Extratropical  1996  40.42105      991.2526
## 3  Extratropical  1997  38.94737      999.7632
## 4  Extratropical  1998  42.92208      990.6104
## 5  Extratropical  1999  38.86364      992.0909
## 6  Extratropical  2000  39.68254      996.7619
## 7      Hurricane  1995  81.99187      969.6016
## 8      Hurricane  1996  85.50336      969.1275
## 9      Hurricane  1997  80.39474      976.3947
## 10     Hurricane  1998  87.04142      972.4260
## # ... with 14 more rows</code></pre>
<p>This calculates mean wind speed and atmospheric pressure for different combination of <code>type</code> and <code>year</code>. The first line shows us that the mean wind speed and pressure associated with extra-tropical storms in 1995 was 38.7 mph and 995 millibars, the second line shows us that the mean wind speed and pressure associated with extra-tropical storms in 1995 was 40.4 mph and 991 millibars, and so on. There are 24 rows in total because there were 24 unique combinations of <code>type</code> and <code>year</code> in the original <code>storms_tbl</code>.</p>
</div>
<div id="using-group_by-with-other-verbs" class="section level3">
<h3><span class="header-section-number">15.2.2</span> Using <code>group_by</code> with other verbs</h3>
<p>The <code>summarise</code> function is the only <strong>dplyr</strong> verb we’ll use with grouped tibbles in this book. However, all the main verbs alter their behaviour to respect group identity when used with tibbles with grouping information. When <code>mutate</code> or <code>transmute</code> are used with a grouped object they still add new variables, but now the calculations occur “by group”. Here’s an example using <code>transmute</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># group the storms data by storm name + assign the result a name</span>
storms_grouped &lt;-<span class="st"> </span><span class="kw">group_by</span>(storms_tbl, name)
<span class="co"># create a data set &#39;mean centred&#39; wind speed variable</span>
<span class="kw">transmute</span>(storms_grouped, <span class="dt">wind_centred =</span> wind -<span class="st"> </span><span class="kw">mean</span>(wind))</code></pre></div>
<pre><code>## Adding missing grouping variables: `name`</code></pre>
<pre><code>## Source: local data frame [2,747 x 2]
## Groups: name [79]
## 
##       name wind_centred
##      &lt;chr&gt;        &lt;dbl&gt;
## 1  Allison   -14.393939
## 2  Allison   -14.393939
## 3  Allison    -9.393939
## 4  Allison    -4.393939
## 5  Allison     5.606061
## 6  Allison    15.606061
## 7  Allison    20.606061
## 8  Allison    20.606061
## 9  Allison    20.606061
## 10 Allison    15.606061
## # ... with 2,737 more rows</code></pre>
<p>In this example we calculated the “group mean-centered” version of the wind variable. The new <code>wind_centred</code> variable contains the difference between the wind speed and the mean of whichever storm type is associated with the observation.</p>
</div>
</div>
<div id="removing-grouping-information" class="section level2">
<h2><span class="header-section-number">15.3</span> Removing grouping information</h2>
<p>On occasion it’s necessary to remove grouping information from a data object. This is most often done when working with “pipes” (the topic of the next chapter) when we need to revert back to operating on the whole data set. The <code>ungroup</code> function removes grouping information:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ungroup</span>(storms_grouped)</code></pre></div>
<pre><code>## # A tibble: 2,747 × 11
##       name  year month   day  hour   lat  long pressure  wind
##      &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;int&gt; &lt;int&gt;
## 1  Allison  1995     6     3     0  17.4 -84.3     1005    30
## 2  Allison  1995     6     3     6  18.3 -84.9     1004    30
## 3  Allison  1995     6     3    12  19.3 -85.7     1003    35
## 4  Allison  1995     6     3    18  20.6 -85.8     1001    40
## 5  Allison  1995     6     4     0  22.0 -86.0      997    50
## 6  Allison  1995     6     4     6  23.3 -86.3      995    60
## 7  Allison  1995     6     4    12  24.7 -86.2      987    65
## 8  Allison  1995     6     4    18  26.2 -86.2      988    65
## 9  Allison  1995     6     5     0  27.6 -86.1      988    65
## 10 Allison  1995     6     5     6  28.5 -85.6      990    60
## # ... with 2,737 more rows, and 2 more variables: type &lt;chr&gt;,
## #   seasday &lt;int&gt;</code></pre>
<p>Looking at the top right of the printed summary, we can see that the <code>Group:</code> part is now gone—the <code>ungroup</code> function effectively created a copy of <code>storms_grouped</code> that is identical to the original <code>storms_tbl</code> tibble.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="helper-functions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="building-piplines.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/dzchilds/eda-for-bio/edit/master/2_07_dplyr_summaries_groups.Rmd",
"text": "Edit"
},
"download": null,
"toc": {
"collapse": "section"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
